export const apps = [
    '1Password',
    'Calendar',
    'Camera',
    'Chrome',
    'Clock',
    'Contacts',
    'Docs',
    'Drive',
    'Emergency',
    'Files',
    'Github',
    'Gmail',
    'Google Fit',
    'Google Home',
    'Google Memo',
    'Google News',
    'Google One',
    'Google Podcasts',
    'Google TV',
    'Kyash',
    'Map',
    'Messages',
    'Pay Pay',
    'Phone',
    'Photos',
    'Playstore',
    'Recording',
    'Settings',
    'Shazam',
    'Slack',
    'Slides',
    'Sofa Score',
    'Spotify',
    'Translate',
    'Tusker',
    'Twitter',
    'Unext',
    'Wallet',
    'WearOS',
    'Whatsapp',
    'Wise',
    'Youtube Music',
    'Youtube'
]