export const apps = [
    {name: '1Password', file: '1Password', playstore: 'com.onepassword.android'},
    {name: 'Family Link parental controls', file: 'Accessibility', playstore: 'com.google.android.apps.kids.familylinkhelper'},
    {name: 'Bitwarden', file: 'Bitwarden', playstore: 'com.x8bit.bitwarden'},
    {name: 'Brave', file: 'Brave', playstore: 'com.brave.browser'},
    {name: 'Samsung Browser', file: 'Browser', playstore: 'com.sec.android.app.sbrowser'},
    {name: 'Calculator', file: 'Calculator', playstore: 'com.google.android.calculator'},
    {name: 'Calendar', file: 'Calendar', playstore: 'com.google.android.calendar'},
    {name: 'Camera', file: 'Camera', playstore: 'com.google.android.GoogleCamera'},
    {name: 'Chrome Beta', file: 'Chrome Beta', playstore: 'com.chrome.beta'},
    {name: 'Chrome', file: 'Chrome', playstore: 'com.android.chrome'},
    {name: 'Clock', file: 'Clock', playstore: 'com.google.android.deskclock'},
    {name: 'Contacts', file: 'Contacts', playstore: 'com.google.android.contacts'},
    {name: 'Docs', file: 'Docs', playstore: 'com.google.android.apps.docs.editors.docs'},
    {name: 'Doodle: Live Wallpapers', file: 'Doodle', playstore: 'xyz.zedler.patrick.doodle'},
    {name: 'DoorDash', file: 'DoorDash', playstore: 'com.dd.doordash'},
    {name: 'Drive', file: 'Drive', playstore: 'com.google.android.apps.docs'},
    {name: 'DroidKaigi\'22', file: 'DroidKaigi 2022', playstore: 'io.github.droidkaigi.confsched2022'},
    {name: 'DuckDuckGo', file: 'DuckDuckGo', playstore: 'com.duckduckgo.mobile.android'},
    {name: 'Personal Safety', file: 'Emergency', playstore: 'com.google.android.apps.safetyhub'},
    {name: 'Files', file: 'Files', playstore: 'com.google.android.apps.nbu.files'},
    {name: 'Find My Phone', file: 'Find My Phone', playstore: 'com.google.android.apps.adm'},
    {name: 'Firefox', file: 'Firefox', playstore: '=org.mozilla.firefox'},
    {name: 'Gallery', file: 'Gallery', playstore: 'com.google.android.apps.photosgo'},
    {name: 'Geekbench 6', file: 'Geekbench 6', playstore: 'com.primatelabs.geekbench6'},
    {name: 'Github', file: 'Github', playstore: 'com.github.android'},
    {name: 'Gmail', file: 'Gmail', playstore: 'com.google.android.gm'},
    {name: 'Google Assistant', file: 'Google Assistant', playstore: 'com.google.android.apps.googleassistant'},
    {name: 'Google Fi', file: 'Google Fi', playstore: 'com.google.android.apps.tycho'},
    {name: 'Google Fit', file: 'Google Fit', playstore: 'com.google.android.apps.fitness'},
    {name: 'Google Home', file: 'Google Home', playstore: 'com.google.android.apps.chromecast.app'},
    {name: 'Google Lens', file: 'Google Lens', playstore: 'com.google.android.apps.googleassistant'},
    {name: 'Google Meet', file: 'Google Meet', playstore: 'com.google.android.apps.googleassistant'},
    {name: 'Google Keep', file: 'Google Memo', playstore: 'com.google.android.keep'},
    {name: 'Google News', file: 'Google News', playstore: 'com.google.android.apps.magazines'},
    {name: 'Google One', file: 'Google One', playstore: 'com.google.android.apps.subscriptions.red'},
    {name: 'Google Podcasts', file: 'Google Podcasts', playstore: 'com.google.android.apps.podcasts'},
    {name: 'Google Sheets', file: 'Google Sheets', playstore: 'com.google.android.apps.docs.editors.sheets'},
    {name: 'Google TV', file: 'Google TV', playstore: 'com.google.android.videos'},
    {name: 'Google', file: 'Google', playstore: 'com.google.android.apps.googleassistant'},
    {name: 'Kyash', file: 'Kyash', playstore: 'co.kyash'},
    {name: 'LinkedIn', file: 'LinkedIn', playstore: 'com.linkedin.android'},
    {name: 'Maps', file: 'Map', playstore: 'com.google.android.apps.maps'},
    {name: 'Messages', file: 'Messages', playstore: 'com.google.android.apps.messaging'},
    {name: 'Microsoft Edge', file: 'Microsoft Edge', playstore: 'com.microsoft.emmx'},
    {name: 'NordVPN', file: 'NordVPN', playstore: 'com.google.android.apps.googleassistant'},
    {name: 'Opera', file: 'Opera', playstore: 'com.opera.browser'},
    {name: 'PayPay', file: 'Pay Pay', playstore: 'jp.ne.paypay.android.app'},
    {name: 'Phone', file: 'Phone', playstore: 'com.google.android.dialer'},
    {name: 'Photos', file: 'Photos', playstore: 'com.google.android.apps.photos'},
    {name: 'Pixel Guide', file: 'Pixel Guide', playstore: 'com.google.android.apps.googleassistant'},
    {name: 'Play Books', file: 'Play Books', playstore: 'com.google.android.apps.googleassistant'},
    {name: 'Play Games', file: 'Play Games', playstore: 'com.google.android.apps.googleassistant'},
    {name: 'Playstore', file: 'Playstore', playstore: ''},
    {name: 'Reading Mode', file: 'Reading', playstore: 'com.google.android.apps.googleassistant'},
    {name: 'Recorder', file: 'Recording', playstore: 'com.google.android.apps.recorder'},
    {name: 'Settings', file: 'Settings', playstore: ''},
    {name: 'Shazam', file: 'Shazam', playstore: 'com.shazam.android'},
    {name: 'Slack', file: 'Slack', playstore: 'com.Slack'},
    {name: 'Google Slides', file: 'Slides', playstore: 'com.google.android.apps.docs.editors.slides'},
    {name: 'Sofascore', file: 'Sofa Score', playstore: 'com.sofascore.results'},
    {name: 'Spotify', file: 'Spotify', playstore: 'com.spotify.music'},
    {name: 'Swiggy', file: 'Swiggy', playstore: 'in.swiggy.android'},
    {name: 'Telegram', file: 'Telegram', playstore: 'org.telegram.messenger'},
    {name: 'Google Tasks', file: 'Todo List', playstore: 'com.google.android.apps.tasks'},
    {name: 'Translate', file: 'Translate', playstore: 'com.google.android.apps.translate'},
    {name: 'Tusky', file: 'Tusker', playstore: 'com.keylesspalace.tusky'},
    {name: 'Twitter', file: 'Twitter', playstore: 'com.twitter.android'},
    {name: 'Unext', file: 'Unext', playstore: 'jp.unext.mediaplayer'},
    {name: 'Google Voice', file: 'Voice', playstore: 'com.google.android.apps.googlevoice'},
    {name: 'Wallet', file: 'Wallet', playstore: 'com.google.android.apps.walletnfcrel'},
    {name: 'Pixel Watch', file: 'Watch', playstore: 'com.google.android.apps.wear.companion'},
    {name: 'WearOS', file: 'WearOS', playstore: 'com.google.android.wearable.app'},
    {name: 'Whatsapp', file: 'Whatsapp', playstore: 'com.whatsapp'},
    {name: 'Wise', file: 'Wise', playstore: 'com.transferwise.android'},
    {name: 'Youtube Music', file: 'Youtube Music', playstore: 'com.google.android.youtube.tvmusic'},
    {name: 'Youtube', file: 'Youtube', playstore: 'com.google.android.youtube'}
]